# Model parameters:
in_channels: 3
image_size: 256
num_residuals: 8

# Training process:
num_epochs: 100
batch_size: 1
generator_learning_rate: 0.0003
discriminator_learning_rate: 0.0003
lambda_cycle: 3
load_checkpoint: F
save_checkpoint: true
num_workers: 2

# Dataset:
train_dir: dataset/train
dataset_mean: [0.5, 0.5, 0.5]
dataset_std: [0.5, 0.5, 0.5]

# Checkpoints:
checkpoint_dir: checkpoints
